name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/generate-sbom.yml
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/generate-sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate front-end SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@d39a08b2145375940f52c0b4b8c58a8cf3603bdb
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-documentation/app
          project_type: node          
