name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/generate-sbom.yml
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/generate-sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2

      - name: Generate front-end SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@14ab23f07437d642594c56003db1f4bd34e54bbb # renovate: tag=v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-documentation/app
          project_type: node          
